### ISSUE TITLE
send management message

### ISSUE THREAD

**Issue by adobemomo** [6156-superstainsocket/match-group-microservice#12]
When a user is invited to a new group, a new message needs to be sent to admin

**Comment by JoanWu5** [comment]
only when the allow_without_approval = false, the admin should get the message

**Comment by adobemomo** [comment]
test plz :)

**Comment by JoanWu5** [comment]
could you also show the body of POST message? I am afraid the info you give is still not enough, I need group info such as groupId, group iconid, group name
![image](https://user-images.githubusercontent.com/37609013/208452631-012baf56-fd53-44f4-9fcd-a34877d7e412.png)

**Comment by JoanWu5** [comment]
please see https://github.com/6156-superstainsocket/match-group-microservice/issues/19, it has a general body example

**Comment by adobemomo** [comment]
info is similar to #19
