### ISSUE TITLE
PUT /groups/:gid/users/:uid failed

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#15]
![image](https://user-images.githubusercontent.com/37609013/208272646-8c8bcdec-b471-4160-91d6-c9fbd4978248.png)
Why there is a group needed? as gid is in the path

**Comment by adobemomo** [comment]
@JoanWu5  probably fixed. please take a look and test again.

**Comment by JoanWu5** [comment]
still 500,
`curl -X PUT http://match-group-microservice-dev.us-east-1.elasticbeanstalk.com/api/groups/38/users/27 -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxOTM4MjY4LCJpYXQiOjE2NzEzMzM0NjgsImp0aSI6IjRmNWNhNjMwZDY4YTQ5ZTViNTFiZmYzOGIyMDcxNWMyIiwidXNlcl9pZCI6MjcsInVzZXIiOnsiaWQiOjI3LCJ1c2VybmFtZSI6IjEyM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InBia2RmMl9zaGEyNTYkMzkwMDAwJDk1QUVta1RjRkM0REFiSUxwa0tVU0UkbVF1bVVHT3BqdURaMU1KUUlFQTdrUjloaGtJV3duUmdIak1ZcDAwSm5zYz0iLCJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiTGkiLCJwcm9maWxlIjp7ImlkIjoyNSwiaXNfZ29vZ2xlIjp0cnVlLCJuYW1lIjoiIiwicGhvbmUiOiIxMjM0NTYiLCJkZXNjcmlwdGlvbiI6IiIsImljb25pZCI6MSwidXNlciI6Mjd9fX0.SgijcMP5LHHn4kH4jKneAukNPoWapzejwJdffF6o8PA'`

**Comment by JoanWu5** [comment]
`curl -X PUT http://match-group-microservice-dev.us-east-1.elasticbeanstalk.com/api/groups/38/users/27 -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxOTM4MjY4LCJpYXQiOjE2NzEzMzM0NjgsImp0aSI6IjRmNWNhNjMwZDY4YTQ5ZTViNTFiZmYzOGIyMDcxNWMyIiwidXNlcl9pZCI6MjcsInVzZXIiOnsiaWQiOjI3LCJ1c2VybmFtZSI6IjEyM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InBia2RmMl9zaGEyNTYkMzkwMDAwJDk1QUVta1RjRkM0REFiSUxwa0tVU0UkbVF1bVVHT3BqdURaMU1KUUlFQTdrUjloaGtJV3duUmdIak1ZcDAwSm5zYz0iLCJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiTGkiLCJwcm9maWxlIjp7ImlkIjoyNSwiaXNfZ29vZ2xlIjp0cnVlLCJuYW1lIjoiIiwicGhvbmUiOiIxMjM0NTYiLCJkZXNjcmlwdGlvbiI6IiIsImljb25pZCI6MSwidXNlciI6Mjd9fX0.SgijcMP5LHHn4kH4jKneAukNPoWapzejwJdffF6o8PA'`

**Comment by JoanWu5** [comment]
![image](https://user-images.githubusercontent.com/37609013/208280279-c2a13d42-2829-4703-b8db-945c0e0b4018.png)

**Comment by JoanWu5** [comment]
new token
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxOTM5OTk3LCJpYXQiOjE2NzEzMzUxOTcsImp0aSI6ImNlMzM5ZDA2NTUzYjQ4M
WE5N2Y0OGE2MWMzZGU1MGNiIiwidXNlcl9pZCI6MjcsInVzZXIiOnsiaWQiOjI3LCJ1c2VybmFtZSI6IjEyM0BnbWFpbC5jb20iLCJwYXNzd29yZCI6InBia2RmMl9zaGEyNTYkMzkwMDA
wJDk1QUVta1RjRkM0REFiSUxwa0tVU0UkbVF1bVVHT3BqdURaMU1KUUlFQTdrUjloaGtJV3duUmdIak1ZcDAwSm5zYz0iLCJlbWFpbCI6IjEyM0BnbWFpbC5jb20iLCJmaXJzdF9uYW1lI
joiIiwibGFzdF9uYW1lIjoiTGkiLCJwcm9maWxlIjp7ImlkIjoyNSwiaXNfZ29vZ2xlIjp0cnVlLCJuYW1lIjoiIiwicGhvbmUiOiIxMjM0NTYiLCJkZXNjcmlwdGlvbiI6IiIsImljb25
pZCI6MSwidXNlciI6Mjd9fX0.pdSgx60cYnpUJQvznHUBE-EYgHl5dSgP8uZps90kdW4`

**Comment by JoanWu5** [comment]
solved
