### ISSUE TITLE
ignore repeated invitation

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#18]
比如A邀请B，B加入了group，然后A再次邀请, 就应该忽略B，否则B的message消息里面会有重复的，除非是B quit了，A再邀请，这样B得消息里才会出现多次加入group邀请

**Comment by adobemomo** [comment]
I checked the current logic again; this should be fine since only when there's no record of user A and group G will the message be sent out.

**Comment by JoanWu5** [comment]
ok
