### ISSUE TITLE
invitation error when allow_without_approval=false

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#22]
我邀请了1@gmail.com然后跪了，报错是Object of type Group is not JSON serializable
然后我想问下如果allow_without_approval=false， admin邀请别人的话是不是没有admin approve这一步？

**Comment by adobemomo** [comment]
should be fine now.

and yes.

**Comment by JoanWu5** [comment]
我还发现了一个bug，我是user 35，我group id 38里面的userId 27邀请29成功了，allow_without_approve是false, 但是呢，我29 invitation message 里面啥也没有，35management message里面也没有

**Comment by JoanWu5** [comment]
@adobemomo

**Comment by JoanWu5** [comment]
现在29 accept成功了，但是admin没approve，admin是35登陆发现management message里面啥也没有

**Comment by JoanWu5** [comment]
group 39

**Comment by adobemomo** [comment]
should be fine now

**Comment by JoanWu5** [comment]
solved
