### ISSUE TITLE
invitation wrong

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#23]
find a wrong invitation message, I invite myself to join a group
It can be either
1. the backend doesn't restrict I invite myself
2. or POST message from_user and to_user is reversed?

**Comment by JoanWu5** [comment]
我还发现了一个bug，我是user 35，我group id 38里面的userId 27邀请29成功了，allow_without_approve是false, 但是呢，我29 invitation message 里面啥也没有，35management message里面也没有

**Comment by adobemomo** [comment]
the situation 1 fits. already fixed, and please check :)

**Comment by JoanWu5** [comment]
solved
