### ISSUE TITLE
group user member wrong

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#24]
Please login in https://d11pazxn2nhb35.cloudfront.net/#/
using 123@gmail.com and 123
then click group "test for link"
there is 1 member but not me(123), so why can I see this group?

**Comment by JoanWu5** [comment]
我发现是A invite B，B还没有同意，B就能看到A在的那个group了，这肯定是不对的

**Comment by JoanWu5** [comment]
GET /groups/:gid/users返回的应该是both user_approved=true 和admin_approved =true的吧

**Comment by adobemomo** [comment]
should be fine now :)

**Comment by JoanWu5** [comment]
solved
