### ISSUE TITLE
[IMPORTANT] error with /api/groups/:gid/users/:uid throws 500

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#4]
`curl http://match-group-microservice-dev.us-east-1.elasticbeanstalk.com/api/groups/20/users/27 -H "Accept: application/json" -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNjgyOTc5LCJpYXQiOjE2NzEwNzgxNzksImp0aSI6IjNkNDYxOWU1OTYxMjQxY2E5ZDEyYTE5M2Y2NTA3OWRiIiwidXNlcl9pZCI6MzUsInVzZXIiOnsiaWQiOjM1LCJ1c2VybmFtZSI6ImpvYW5uZG13QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicGJrZGYyX3NoYTI1NiQzOTAwMDAkSng1U2FxUEh5WndveGtzZTlYSEhMcyRUOU9qNHQvUEpNTGFVeFQrSnk2RGFDanFXZGNvVml0SnJiZVNqUzFQUWprPSIsImVtYWlsIjoiam9hbm5kbXdAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsInByb2ZpbGUiOnsiaWQiOjMxLCJpc19nb29nbGUiOnRydWUsIm5hbWUiOiJEYW5tZWkgV3UyIiwicGhvbmUiOiIxMjMtNDU2LTc4OTAiLCJkZXNjcmlwdGlvbiI6InRoaXMgaXMgZGVzY3JpcHRpb24gYWJvdXQgbWUiLCJpY29uaWQiOjIsInVzZXIiOjM1fX19.Moo1U60-yGpWYM84axdAX9v-cSD6pXI3wBElSGXJNvo"`

**Comment by JoanWu5** [comment]
tags should be the login user tags uid person, not the group overall tags

**Comment by JoanWu5** [comment]
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjcxNjgyOTc5LCJpYXQiOjE2NzEwNzgxNzksImp0aSI6IjNkNDYxOWU1OTYxMjQxY2E5ZDEyYTE5M2Y2NTA3OWRiIiwidXNlcl9pZCI6MzUsInVzZXIiOnsiaWQiOjM1LCJ1c2VybmFtZSI6ImpvYW5uZG13QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoicGJrZGYyX3NoYTI1NiQzOTAwMDAkSng1U2FxUEh5WndveGtzZTlYSEhMcyRUOU9qNHQvUEpNTGFVeFQrSnk2RGFDanFXZGNvVml0SnJiZVNqUzFQUWprPSIsImVtYWlsIjoiam9hbm5kbXdAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsInByb2ZpbGUiOnsiaWQiOjMxLCJpc19nb29nbGUiOnRydWUsIm5hbWUiOiJEYW5tZWkgV3UyIiwicGhvbmUiOiIxMjMtNDU2LTc4OTAiLCJkZXNjcmlwdGlvbiI6InRoaXMgaXMgZGVzY3JpcHRpb24gYWJvdXQgbWUiLCJpY29uaWQiOjIsInVzZXIiOjM1fX19.Moo1U60-yGpWYM84axdAX9v-cSD6pXI3wBElSGXJNvo

**Comment by adobemomo** [comment]
@JoanWu5 please take a look

**Comment by JoanWu5** [comment]
solved
