### ISSUE TITLE
[IMPORTANT] user info uncomplete with api/groups/20/users

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#5]
It should contains all user information like the following one user
![image](https://user-images.githubusercontent.com/37609013/207904032-ebccd7ad-a1a7-4402-8214-039cdc0a8608.png)

**Comment by JoanWu5** [comment]
tag should be the login user tags uid person, not the group overall tags

**Comment by adobemomo** [comment]
@JoanWu5  Probably fixed

**Comment by JoanWu5** [comment]
solved
