### ISSUE TITLE
[IMPORTANT] create group issue

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#6]
1. why description cannot be empty？
2. And the tag name, description and icon id should be the following:
```
final List<Tag> defaultTags = [
  Tag(
    name: 'dinner',
    description: 'I want to have dinner with her/him',
    iconId: 0,
  ),
  Tag(
    name: 'date',
    description: 'I want to date her/him',
    iconId: 1,
  ),
  Tag(
    name: 'study',
    description: 'I want to study with her/him',
    iconId: 2,
  ),
];
```
3. And please delete the groups without default tags

**Comment by JoanWu5** [comment]
the icon_id is still all 1, please see above example, it should be 0, 1, 2

**Comment by JoanWu5** [comment]
the icon_id is still all 1, please see above example, it should be 0, 1, 2

**Comment by adobemomo** [comment]
It should be fixed now. Please take a look.

**Comment by JoanWu5** [comment]
solved
