### ISSUE TITLE
[IMPORTANT]email invitation api input is not correct

### ISSUE THREAD

**Issue by JoanWu5** [6156-superstainsocket/match-group-microservice#9]
I am wondering what API it is?
The input body should be a list of emails.
![image](https://user-images.githubusercontent.com/37609013/208204317-e1d58054-93f7-45fb-ba65-a57c750966bc.png)

**Comment by adobemomo** [comment]
I don't think we discussed this API before. It's not in the document. The current invitation API is as follows:

![image](https://user-images.githubusercontent.com/39028148/208216293-f2e56af3-dce5-44f5-b4c3-b6d44f888c46.png)

the batch invitation is not supported yet.

**Comment by JoanWu5** [comment]
As discussed,  I will call user batch and then call post invitation batch, **please support batch invitation users**

**Comment by JoanWu5** [comment]
I can first use individual invitation to test

**Comment by adobemomo** [comment]
- [ ] change API to batch invite, POST body param: {"emails": []} , /groups/gid/users

**Comment by JoanWu5** [comment]
It throws 500
![image](https://user-images.githubusercontent.com/37609013/208249765-3f754714-eb2a-48f8-a1bf-a6bc6f658f21.png)

**Comment by adobemomo** [comment]
add env variable, should work now @JoanWu5

**Comment by JoanWu5** [comment]
solved
